name: sample_structure
description: A sample structure for flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.19.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    intl: ^0.17.0

    flutter_localizations:
        sdk: flutter
    shared_preferences: ^2.1.0
    package_info_plus: ^3.1.0
    internet_connection_checker: ^1.0.0+1
    fluttertoast: ^8.2.1
    timeago: ^3.3.0
    cached_network_image: ^3.2.3
    flutter_svg: ^2.0.5
    photo_view: ^0.14.0
    shimmer: ^2.0.0
    flash_image: ^0.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    generate: true
    uses-material-design: true
    assets:
        - assets/images
        - assets/icons

    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/roboto/Roboto-Thin-100.ttf
                weight: 100
              - asset: assets/fonts/roboto/Roboto-Light-300.ttf
                weight: 300
              - asset: assets/fonts/roboto/Roboto-Regular-400.ttf
                weight: 400
              - asset: assets/fonts/roboto/Roboto-Medium-500.ttf
                weight: 500
              - asset: assets/fonts/roboto/Roboto-Bold-700.ttf
                weight: 700
              - asset: assets/fonts/roboto/Roboto-Black-900.ttf
                weight: 900
